# Generated by Django 3.2 on 2022-10-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_ADD_job1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField(max_length=200, null=True)),
                ('cname', models.TextField(max_length=500, null=True)),
                ('vaccancy', models.TextField(max_length=500, null=True)),
                ('place', models.TextField(max_length=500, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('ex', models.TextField(max_length=500, null=True)),
                ('qua', models.TextField(max_length=500, null=True)),
                ('quan', models.TextField(max_length=500, null=True)),
                ('des', models.TextField(max_length=500, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='C_ADDed_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField(max_length=200, null=True)),
                ('cname', models.TextField(max_length=500, null=True)),
                ('vaccancy', models.TextField(max_length=500, null=True)),
                ('place', models.TextField(max_length=500, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('ex', models.TextField(max_length=500, null=True)),
                ('qua', models.TextField(max_length=500, null=True)),
                ('quan', models.TextField(max_length=500, null=True)),
                ('des', models.TextField(max_length=500, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='DETAIL_APPLY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField(max_length=200, null=True)),
                ('cname', models.TextField(max_length=500, null=True)),
                ('place', models.TextField(max_length=500, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('qua', models.TextField(max_length=500, null=True)),
                ('quan', models.TextField(max_length=500, null=True)),
                ('sname', models.TextField(max_length=500, null=True)),
                ('ex', models.TextField(max_length=500, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('cv', models.FileField(null=True, upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='G_ADD_guidance1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.TextField(max_length=200, null=True)),
                ('number', models.IntegerField(null=True)),
                ('ctime', models.TextField(max_length=100, null=True)),
                ('place', models.TextField(max_length=500, null=True)),
                ('rfee', models.IntegerField(null=True)),
                ('qua', models.TextField(max_length=500, null=True)),
                ('quan', models.TextField(max_length=500, null=True)),
                ('des', models.TextField(max_length=500, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='logsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='regsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('mail', models.CharField(max_length=15, null=True)),
                ('mark', models.TextField(max_length=15, null=True)),
                ('number', models.TextField(max_length=15, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('re_pass', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegsaveC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('mail', models.CharField(max_length=15, null=True)),
                ('jobcate', models.TextField(max_length=15, null=True)),
                ('year', models.IntegerField(null=True)),
                ('number', models.TextField(max_length=15, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('re_pass', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegsaveG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('mail', models.CharField(max_length=15, null=True)),
                ('course', models.TextField(max_length=15, null=True)),
                ('year', models.IntegerField(null=True)),
                ('number', models.TextField(max_length=15, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('re_pass', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
