# Generated by Django 3.2 on 2022-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_detail_apply_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_Details1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=15, null=True)),
                ('location', models.TextField(max_length=15, null=True)),
                ('year', models.IntegerField(null=True)),
                ('number', models.TextField(max_length=15, null=True)),
                ('cname', models.CharField(max_length=8, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
