# Generated by Django 3.2 on 2022-10-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_s_details1'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_USER1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, null=True)),
                ('pname', models.TextField(max_length=500, null=True)),
                ('email', models.TextField(max_length=500, null=True)),
                ('number', models.TextField(max_length=500, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('ex', models.TextField(max_length=500, null=True)),
                ('file', models.FileField(null=True, upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='G_USER1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, null=True)),
                ('cname', models.TextField(max_length=500, null=True)),
                ('email', models.TextField(max_length=500, null=True)),
                ('number', models.TextField(max_length=500, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('qua', models.TextField(max_length=500, null=True)),
                ('file', models.FileField(null=True, upload_to='file/')),
            ],
        ),
    ]
