# Generated by Django 3.2 on 2022-10-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_c_user1_g_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=15, null=True)),
                ('month', models.CharField(max_length=15, null=True)),
                ('location', models.TextField(max_length=15, null=True)),
                ('cs', models.IntegerField(null=True)),
                ('number', models.TextField(max_length=15, null=True)),
                ('ctime', models.CharField(max_length=8, null=True)),
                ('img', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
