# Generated by Django 3.2 on 2022-10-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_c_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_details',
            name='cs',
            field=models.TextField(null=True),
        ),
    ]
