# Generated by Django 3.2 on 2022-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_c_details_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='regsave',
            name='type',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
