# Generated by Django 3.2 on 2022-10-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_regsave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regsave',
            name='type',
        ),
    ]
