from django.urls import path

from myapp import views

urlpatterns = [
    path('homeview',views.homeview,name='homeview'),
    path('Viewlogout',views.Viewlogout,name="Viewlogout"),
    path('home1',views.login1,name="home1"),
    path('home2/',views.register1,name="home2"),
    path('home3/',views.registersave,name="home3"),
    path('register2',views.register2,name="register2"),
    path('login2',views.login2,name="login2"),
    path('loginsave',views.loginsave,name="loginsave"),
    path('Gregistersave',views.Gregistersave,name="Gregistersave"),
    path('home5/',views.adminlogin,name="home5"),
    path('',views.Userindex,name="home6"),
    path('home8/',views.logchk,name="home8"),
    path('user_contact',views.user_contact,name='user_contact'),
    path('CG_details',views.CG_details,name='CG_details'),
    path('IndexAdmin',views.IndexAdmin,name='IndexAdmin'),
    path('register3',views.register3,name="register3"),
    path('login3',views.login3,name="login3"),
    path('loginsave3',views.loginsave3,name="loginsave3"),
    path('Cregistersave',views.Cregistersave,name="Cregistersave"),
    path('Company_index',views.Company_index,name='Company_index'),
    path('Company_contact',views.Company_contact,name='Company_contact'),
    path('Company_details',views.Company_details,name='Company_details'),
    path('Company_about',views.Company_about,name='Company_about'),
    path('Company_job',views.Company_job,name='Company_job'),
    path('c_edit/<int:ceid>/',views.c_edit,name='c_edit'),
    path('c_update/<int:c_id>/',views.c_update,name='c_update'),
    path('c_delete/<int:c_did>/',views.c_delete,name='c_delete'),
    path('ctable',views.ctable,name='ctable'),
    path('c_add',views.c_add,name='c_add'),
    path('Guidance_job',views.Guidance_job,name='Guidance_job'),
    path('g_edit/<int:geid>/',views.g_edit,name='g_edit'),
    path('g_update/<int:g_id>/',views.g_update,name='g_update'),
    path('g_delete/<int:g_did>/',views.g_delete,name='g_delete'),
    path('gtable',views.gtable,name='gtable'),
    path('ga_add',views.ga_add,name='ga_add'),
    path('a_add',views.a_add,name='a_add'),
    path('apply_details',views.apply_details,name='apply_details'),
    path('Cuser',views.Cuser,name='Cuser'),
    path('U_user',views.U_user,name='U_user'),
    path('C_shedule',views.C_shedule,name='C_shedule'),
    path('sd',views.sd,name='sd'),
    path('ld',views.ld,name='ld'),
    path('s_add_d',views.s_add_d,name='s_add_d'),
    path('admin_c_table',views.admin_c_table,name='admin_c_table'),
    path('guidance_details',views.guidance_details,name='guidance_details'),
    path('g_add',views.g_add,name='g_add'),
    path('u_add',views.u_add,name='u_add'),
    path('admin_d',views.admin_d,name='admin_d'),
    path('ad',views.ad,name='ad'),
    path('c_d',views.c_d,name='c_d'),
    path('applyJob_table_admin',views.applyJob_table_admin,name='applyJob_table_admin'),
    path('G_Job_table_admin',views.G_Job_table_admin,name='G_Job_table_admin')

]
